  [en]
    languageName = "English"
    title = "Laurens Wijnsma"
    subtitle = "A simple, retro theme for Hugo"
    owner = "Laurens Wijnsma"
    keywords = ""
    copyright = "Â© 2023 Laurens Wijnsma"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [en.params.logo]
      logoText = "Tweaker33"
      logoHomeLink = "/"
